#!/bin/sh
set -e

knxd -i $KNX_INTERFACE -e $KNX_PA $KNXD_PARAMETERS
chmod a+w /tmp/eib

CGI_URL_PATH=${CGI_URL_PATH:-/cgi-bin/}
if [ "${CGI_URL_PATH:-/cgi-bin/}" != "/cgi-bin/" ]; then
    echo "Non default CGI_URL_PATH detected: '$CGI_URL_PATH'"

    # Tell the CometVisu to path to the login
    echo '<FilesMatch "visu_config.*xml$">'                          >  /var/www/html/.htaccess
    echo "    Header set X-CometVisu-Backend-LoginUrl $CGI_URL_PATH" >> /var/www/html/.htaccess
    echo '</FilesMatch>'                                             >> /var/www/html/.htaccess

    # Pass CometVisu the resource path during the login
    sed -i 's@\\\"s\\\":\\\"SESSION\\\".*}\"@\\\"s\\\":\\\"SESSION\\\", \\\"c\\\": {\\\"baseURL\\\": \\\"'"$CGI_URL_PATH"'\\\"} }"@' /usr/lib/cgi-bin/l
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

exec "$@"