#!/bin/sh
set -e

knxd -i $KNX_INTERFACE -e $KNX_PA $KNXD_PARAMETERS
chmod a+w /tmp/eib

echo $CGI_PATH

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

exec "$@"