#!/bin/sh
set -e

echo "Starting sshd..."
/usr/sbin/sshd

export ADDITIONAL_HEALTHCHECK="if ! pidof sshd >/dev/null; then echo 'Error: knxd not running'; \$badhealth > /dev/null 2>&1; exit 1; fi" >> /usr/local/bin/healthcheck

# pass over to original entrypoint
echo "Passing over to original entrypoint '$@'..."
exec cometvisu-entrypoint "$@"