name: Docker Image CI

on:
  push:
    branches: [ master, source_container ]
  pull_request:
    branches: [ master, source_container ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: christianmayer/developcometvisucontainer:${{ steps.extract_branch.outputs.branch }}-$(date +%s),christianmayer/developcometvisucontainer:${{ steps.extract_branch.outputs.branch }}    
