name: Docker Image CI

on:
  push:
    branches: [ master, source_container ]
  pull_request:
    branches: [ master, source_container ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag christianmayer/developcometvisucontainer:source-$(date +%s)
